import { Panel } from "../designkit/containers.slint";
import { Track, TrackSettings, TrackType } from "../models/models.slint";
import { VerticalBox, ListView } from "std-widgets.slint";
import { State } from "../globals/handlers.slint";


component TrackControls {
    in property <Track> track;
    in property <bool> selected;
    Rectangle {
        states [
            on when selected: {background: blue;}
            off when !selected: {background: black;}
        ]
        Text {
            text: track.settings.name;
            color: white;
        }   
    }
}

component TrackTimeline {
    in property <Track> track;

    Rectangle {
        horizontal-stretch: 1;
        background: black;
    }
}
component ComposerTrackSlot inherits Panel {
    in property <Track> track;
    in-out property cur_track <=> State.cur_track;
    in-out property song <=> State.song;
    property <bool> selected: State.song.tracks[State.cur_track] == track;
    horizontal-stretch: 1;
    HorizontalLayout {
        TrackControls { track: track; selected: selected;}
        TrackTimeline { track: track; }
    }
}
export component ComposerWindow inherits Panel {
    in-out property song <=> State.song;
    horizontal-stretch: 1;
    function make_track(name: string) -> Track {
        return  {
            trackType: TrackType.Midi,
            midi_content: {},
            audio_content: {},                        
            settings: {
                name: name,
            }
        };
    }
    VerticalBox {
        ListView {
            for track in song.tracks:
                ComposerTrackSlot{ 
                    track: track;  
                }
            // for name in ["Track 1"]:
            // ComposerTrackSlot { 
            //             track: make_track(name);  
            // }
        }
    }    
}