/**
Components that are no longer in use
*/
import { Button } from "std-widgets.slint";
import { Handlers } from "../globals/handlers.slint";

export component PatternSelector inherits Rectangle {
    in-out property<int> pattern_num;
    HorizontalLayout {
        Button {
            enabled: pattern_num > 0;
            text: "<";
            clicked => {
                pattern_num = max(0, pattern_num - 1);
                Handlers.pattern-changed();
            }
        }
        Text { text: pattern_num; }
        Button {
            text: ">";
            clicked => {
                pattern_num = pattern_num + 1;
                Handlers.pattern-changed();
            }
        }

    }
}