import { Pattern } from "../models/models.slint";
import { Handlers } from "../globals/handlers.slint";

component PatternPadButton inherits Rectangle {
    in property <string> name;
    in-out property <bool> on;
    callback clicked();
    background: green;

    accessible-role: button;
    accessible-label: self.name;
    accessible-action-default => { /* simulate click */ }

    TouchArea {
        clicked => root.clicked();
    }


    states [
        on when on: {background: blue;}
        off when !on: {background: black;}
    ]
}



export component PatternEditor inherits Rectangle {
    // Grid of notes vs beats to create a midi pattern that can be played on loop
    // TODO: create the grid programatically using a native function
    // function create_pattern(note_values: [int], beats: [int]) -> Pattern {
    //     return {
    //         notes: note_values.length,
    //         beats: beats,
    //         note_values: note_values,
    //         pattern: 
    //     };
    // }
    in-out property<Pattern> pattern; 
    function note(i: int) -> int {
        return floor(i/pattern.beats);
    }
    function beat(i: int) -> int {
        return mod(i, pattern.beats);
    }
    property <length> spacing: 5px;
    function cell_width() -> length {
        return self.width / pattern.beats;
    }
    function cell_height() -> length {
        return self.height / pattern.notes;
    }
    function butt_width() -> length {
        return self.width / pattern.beats - 2 * spacing;
    }
    function butt_height() -> length {
        return self.height / pattern.notes - 2 * spacing;
    }
    function butt_x(i: int) -> length {
        return cell_width()*beat(i)+spacing;
    }
    function butt_y(i: int) -> length {
        return cell_height()*note(i)+spacing;
    }
    for button[i] in pattern.notes*pattern.beats: PatternPadButton {
        name: "Note_" + note(i) + "_Beat_"+ beat(i);
        width: butt_width();
        height: butt_height();
        x: butt_x(i);
        y: butt_y(i);
        on: pattern.pattern[beat(i)][note(i)];
        clicked => {
            self.on = !self.on;
            pattern.pattern[beat(i)][note(i)] = self.on;
            Handlers.save-pattern(root.pattern)
        }
    }
    
}
