enum MidiEventType {
    NoteOn,
    NoteOff,
    ControlChange,
    AllNotesOff,
    AllSoundOff,
    PitchBend,
    ProgramChange,
    ChannelPressure,
    PolyphonicKeyPressure,
    SystemReset
}

struct MidiEvent {
    type: MidiEventType,
    channel: int,
    key: int, // NoteOn, NoteOff, PolyphonicKeyPressure
    vel: int, // NoteOn
    ctrl: int, // Control Change
    value: int, // Control Change, PitchBend, Channel Pressure, PolyphonicKeyPressure
    program_id: int, // Program Change
}

export struct MidiNote {
    key: int,
    vel: int,
    duration: int,
}