import { Handlers } from "handlers.slint";
import { Button, VerticalBox } from "std-widgets.slint";
import { PatternEditor } from "pattern_editor.slint";

component PlayButton inherits Button {
    width: 100px;
    height: 40px;
    text: "Play";
}

component PatternSelector inherits Rectangle {
    in-out property<int> pattern_num;
    HorizontalLayout {
        Button {
            enabled: pattern_num > 0;
            text: "<";
            clicked => {
                pattern_num = max(0, pattern_num - 1);
                Handlers.pattern-changed();
            }
        }
        Text { text: pattern_num; }
        Button {
            text: ">";
            clicked => {
                pattern_num = pattern_num + 1;
                Handlers.pattern-changed();
            }
        }

    }
}
export component MainWindow inherits Window {
    min-width: 400px;
    preferred-height: 500px;
    title: "Composable: Pluggable DAW";
    callback play_midi();
    

    in property<bool> is_playing;

    VerticalBox {
        alignment: center;
        spacing: 5px;
        PatternEditor {
            width: 512px;
            height: 384px;
            pattern <=> Handlers.cur_pattern;
        }
        PatternSelector {
            pattern_num <=> Handlers.cur_pattern_num;
        }
        PlayButton {
            enabled: !is_playing;
            clicked => {
                root.play_midi();
            }
        }
    }
}

