import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Handlers } from "globals/handlers.slint";
import { PatternEditor } from "components/pattern_editor.slint";
import { ControlBar } from "components/control_bar.slint";
import { TrackSettingsEditor } from "components/track_settings.slint";
import { ComposerWindow } from "components/composer_window.slint";
import { AppWindow } from "designkit/containers.slint";


export component MainWindow inherits AppWindow {
    min-width: 400px;
    preferred-height: 500px;
    title: "Composable: Pluggable DAW";
    

    in property<bool> is_playing;

    VerticalBox {
        alignment: start;
        // spacing: 5px;
        ControlBar {}
        HorizontalBox {
            alignment: start;
            TrackSettingsEditor {
                vertical-stretch: 1; 
                width: root.width * 20%;
            }
            VerticalBox {
                alignment: start;
                width: root.width * 60%;
                ComposerWindow {
                    vertical-stretch: 1; 
                    horizontal-stretch: 1;
    
                }
                PatternEditor {
                    vertical-stretch: 1; 
                    horizontal-stretch: 1;
                       
                }
            }
        }
    }
}

