import { MidiNote } from "midi.slint";

export struct Pattern {
    notes: int,
    beats: int,
    note_values: [int],
    pattern: [[bool]],
}

export struct Sequence {
    notes: [{tick: int, note: MidiNote}]
}

struct MidiContent {
    patterns: [{tick: int, pattern: Pattern}],
    sequences: [{tick: int, sequence: Sequence}],
}

struct AudioContent {

}

export enum TrackType { Midi, Audio }

export struct Track {
    trackType: TrackType,
    midi_content: MidiContent,
    audio_content: AudioContent,

}

export struct Song {
    tracks: [Track],
}
